import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { glob } from "glob";
import type { CspData } from "./types.js";
import { NGINX_VARIABLE_SIZE_LIMIT } from "./constants.js";

/**
 * Generates the final Nginx security headers configuration file.
 *
 * This function consolidates all collected SRI hashes, CSP nonces, and third-party
 * domains into a robust Content Security Policy. It also includes other standard
 * security headers like HSTS, X-Frame-Options, and Referrer-Policy.
 *
 * Due to Nginx variable size limits, large CSP policies are automatically chunked
 * into multiple variables.
 *
 * @param {string} distDir - The absolute path to the production build output.
 * @param {CspData} cspData - The data object containing hashes and domains collected during HTML processing.
 */
export async function finalizeCspConfig(distDir: string, cspData: CspData) {
  console.log("[PostBuild] Finalizing CSP and Security Headers...");

  // Hash standalone JS files
  const standaloneScriptHashes = new Set<string>();
  const jsFiles = await glob("**/*.js", { cwd: distDir, absolute: true });
  for (const file of jsFiles) {
    const c = fs.readFileSync(file);
    const h = crypto.createHash("sha512").update(c).digest("base64");
    standaloneScriptHashes.add(`'sha512-${h}'`);
  }

  // Combine collected hashes
  const allScriptHashes = new Set([
    ...standaloneScriptHashes,
    ...cspData.scriptHashes,
  ]);
  const allStyleHashes = cspData.styleHashes;

  /**
   * Helper to chunk a large set of CSP hashes into multiple Nginx variables.
   * This avoids exceeding the ~4KB limit for individual variables in Nginx.
   */
  const chunkHashes = (
    hashes: Set<string>,
    prefix: string,
  ): { vars: string; usage: string } => {
    const list = Array.from(hashes);
    const chunks: string[] = [];
    let current = "";

    for (const h of list) {
      const separator = current ? " " : "";
      const candidate = current + separator + h;
      if (
        Buffer.byteLength(candidate, "utf8") > NGINX_VARIABLE_SIZE_LIMIT &&
        current
      ) {
        chunks.push(current);
        current = h;
      } else {
        current = candidate;
      }
    }
    if (current) chunks.push(current);

    if (chunks.length === 0) return { vars: "", usage: "" };

    const varsDef = chunks
      .map((c, i) => `set $${prefix}_${i + 1} "${c}";`)
      .join("\n");
    const usage = chunks.map((_, i) => `$${prefix}_${i + 1}`).join(" ");
    return { vars: varsDef, usage };
  };

  const scriptChunks = chunkHashes(allScriptHashes, "csp_script");
  const styleChunks = chunkHashes(allStyleHashes, "csp_style");

  const imgSrc = Array.from(cspData.imageDomains)
    .map((d) => `https://${d}`)
    .join(" ");

  // Modern and Strict CSP
  const cspHeader = [
    "default-src 'none'",
    `script-src 'self' 'nonce-$cspNonce' ${scriptChunks.usage}`,
    `style-src 'self' 'nonce-$cspNonce' ${styleChunks.usage}`,
    imgSrc
      ? `img-src 'self' data: ${imgSrc} https://*.jmrp.io`
      : "img-src 'self' data: https://*.jmrp.io",
    "font-src 'self' data:",
    "connect-src 'self' https://api.github.com https://cloudflareinsights.com",
    "media-src 'self'",
    "manifest-src 'self'",
    "frame-src 'none'",
    "object-src 'none'",
    "base-uri 'self'",
    "form-action 'self'",
    "frame-ancestors 'none'",
    "upgrade-insecure-requests",
    "report-uri /csp-report",
  ]
    .map((s) => s.trim())
    .join("; ");

  const permissionsPolicy = [
    "accelerometer=()",
    "autoplay=()",
    "browsing-topics=()",
    "camera=()",
    "encrypted-media=()",
    "fullscreen=()",
    "geolocation=()",
    "gyroscope=()",
    "magnetometer=()",
    "microphone=()",
    "midi=()",
    "payment=()",
    "picture-in-picture=()",
    "publickey-credentials-get=(self)",
    "sync-xhr=()",
    "usb=()",
    "xr-spatial-tracking=()",
  ].join(", ");

  const headerVars = [scriptChunks.vars, styleChunks.vars]
    .filter((v) => v && v.trim() !== "")
    .join("\n");

  const content = `# Security Headers Configuration Generated by Astro Post-Build Integration

${headerVars ? `${headerVars}\n\n` : ""}# HSTS (Strict Transport Security)
add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;

# Anti-Sniffing
add_header X-Content-Type-Options "nosniff" always;

# Frame Options (Prevent Clickjacking)
add_header X-Frame-Options "DENY" always;

# XSS Protection
add_header X-XSS-Protection "1; mode=block" always;

# Referrer Policy
add_header Referrer-Policy "strict-origin-when-cross-origin" always;

# Cross-Origin Policies (COOP, COEP, CORP)
add_header Cross-Origin-Embedder-Policy "require-corp" always;
add_header Cross-Origin-Opener-Policy "same-origin" always;
add_header Cross-Origin-Resource-Policy "same-origin" always;

# Security Cookie (Dummy session cookie with security flags)
add_header Set-Cookie "__Host-Session=1; path=/; Secure; HttpOnly; SameSite=Strict" always;

# Content Security Policy (Prioritizing Hashes with Nonce fallback)
add_header Content-Security-Policy "${cspHeader}" always;

# Permissions Policy
add_header Permissions-Policy "${permissionsPolicy}" always;
`;

  fs.writeFileSync(path.join(distDir, "security_headers.conf"), content);
  console.log("  ✓ Generated security_headers.conf");
}
