import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";

import { type AstroIntegrationLogger } from "astro";
import { glob } from "glob";

import { NGINX_VARIABLE_SIZE_LIMIT } from "./constants.js";
import type { CspData } from "./types.js";

/**
 * Generates the final Nginx security headers configuration file.
 *
 * This function consolidates all collected SRI hashes, CSP nonces, and third-party
 * domains into a robust Content Security Policy. It also includes other standard
 * security headers like HSTS, X-Frame-Options, and Referrer-Policy.
 *
 * Due to Nginx variable size limits, large CSP policies are automatically chunked
 * into multiple variables.
 *
 * @param {string} distDir - The absolute path to the production build output.
 * @param {CspData} cspData - The data object containing hashes and domains collected during HTML processing.
 * @param {AstroIntegrationLogger} logger - The Astro logger instance.
 */
export async function finalizeCspConfig(
  distDir: string,
  cspData: CspData,
  logger: AstroIntegrationLogger,
) {
  logger.info("Finalizing CSP and Security Headers...");

  // Hash standalone JS files in parallel
  const jsFiles = await glob("**/*.js", { cwd: distDir, absolute: true });
  const jsHashPromises = jsFiles.map(async (file) => {
    const content = await fs.promises.readFile(file);
    const hash = crypto.createHash("sha512").update(content).digest("base64");
    return `'sha512-${hash}'`;
  });
  const standaloneScriptHashes = new Set(await Promise.all(jsHashPromises));

  // Combine collected hashes
  const allScriptHashes = new Set([
    ...standaloneScriptHashes,
    ...cspData.scriptHashes,
  ]);
  const allStyleHashes = cspData.styleHashes;

  /**
   * Chunks a large set of CSP hashes into multiple Nginx variables to avoid
   * exceeding the ~4KB individual variable limit.
   */
  const chunkHashes = (
    hashes: Set<string>,
    prefix: string,
  ): { vars: string; usage: string } => {
    const list = [...hashes];
    const chunks: string[] = [];
    let current = "";

    for (const h of list) {
      const separator = current ? " " : "";
      const candidate = current + separator + h;
      if (
        Buffer.byteLength(candidate, "utf-8") > NGINX_VARIABLE_SIZE_LIMIT &&
        current
      ) {
        chunks.push(current);
        current = h;
      } else {
        current = candidate;
      }
    }
    if (current) chunks.push(current);

    if (chunks.length === 0) return { vars: "", usage: "" };

    const varsDef = chunks
      .map((c, i) => `set $${prefix}_${i + 1} "${c}";`)
      .join("\n");
    const usage = chunks.map((_, i) => `$${prefix}_${i + 1}`).join(" ");
    return { vars: varsDef, usage };
  };

  const scriptChunks = chunkHashes(allScriptHashes, "csp_script");
  const styleChunks = chunkHashes(allStyleHashes, "csp_style");

  const imgSrc = [...cspData.imageDomains].map((d) => `https://${d}`).join(" ");

  // Modern and Strict CSP
  // Build directives, filtering empty usage to avoid trailing spaces
  const scriptSrcParts = [
    "'self'",
    "'nonce-$cspNonce'",
    scriptChunks.usage,
  ].filter(Boolean);
  const styleSrcParts = [
    "'self'",
    "'nonce-$cspNonce'",
    styleChunks.usage,
  ].filter(Boolean);

  const cspHeader = [
    "default-src 'none'",
    `script-src ${scriptSrcParts.join(" ")}`,
    `style-src ${styleSrcParts.join(" ")}`,
    imgSrc
      ? `img-src 'self' ${imgSrc} https://*.jmrp.io`
      : "img-src 'self' https://*.jmrp.io",
    "font-src 'self'",
    "connect-src 'self' https://api.github.com https://cloudflareinsights.com https://*.cloudflareinsights.com",
    "media-src 'self'",
    "manifest-src 'self'",
    "frame-src 'none'",
    "object-src 'none'",
    "base-uri 'self'",
    "form-action 'self'",
    "frame-ancestors 'none'",
    "upgrade-insecure-requests",
    "report-uri /csp-report",
  ]
    .map((s) => s.trim())
    .join("; ");

  const permissionsPolicy = [
    "accelerometer=()",
    "autoplay=()",
    "browsing-topics=()",
    "camera=()",
    "encrypted-media=()",
    "fullscreen=()",
    "geolocation=()",
    "gyroscope=()",
    "magnetometer=()",
    "microphone=()",
    "midi=()",
    "payment=()",
    "picture-in-picture=()",
    "publickey-credentials-get=(self)",
    "sync-xhr=()",
    "usb=()",
    "xr-spatial-tracking=()",
  ].join(", ");

  const headerVars = [scriptChunks.vars, styleChunks.vars]
    .filter((v) => v && v.trim() !== "")
    .join("\n");

  const demoSecurityCookieHeader =
    process.env.DEMO_SECURITY_COOKIE === "1"
      ? 'add_header Set-Cookie "__Demo-Security-Flags=1; path=/; Secure; HttpOnly; SameSite=Strict" always;'
      : "# Demo security cookie disabled (set DEMO_SECURITY_COOKIE=1 to enable)";

  const content = `# Security Headers Configuration Generated by Astro Post-Build Integration

${headerVars ? `${headerVars}\n\n` : ""}# HSTS (Strict Transport Security)
add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;

# Anti-Sniffing
add_header X-Content-Type-Options "nosniff" always;

# Frame Options (Prevent Clickjacking)
add_header X-Frame-Options "DENY" always;

# XSS Protection
# Deprecated: modern browsers use Content Security Policy
# add_header X-XSS-Protection "1; mode=block" always;

# Referrer Policy
add_header Referrer-Policy "strict-origin-when-cross-origin" always;

# Cross-Origin Policies (COOP, COEP, CORP)
add_header Cross-Origin-Embedder-Policy "credentialless" always;
add_header Cross-Origin-Opener-Policy "same-origin" always;
add_header Cross-Origin-Resource-Policy "same-origin" always;

# Security Cookies (to satisfy security scanners)
add_header Set-Cookie "__Host-Session=1; path=/; Secure; HttpOnly; SameSite=Strict" always;
add_header Set-Cookie "__Secure-Pref=1; path=/; Secure; HttpOnly; SameSite=Strict" always;

# Security Cookie (Optional demo cookie)
${demoSecurityCookieHeader}

# Content Security Policy (Prioritizing Hashes with Nonce fallback)
add_header Content-Security-Policy "${cspHeader}" always;

# Permissions Policy
add_header Permissions-Policy "${permissionsPolicy}" always;
`;

  await fs.promises.writeFile(
    path.join(distDir, "security_headers.conf"),
    content,
  );
  logger.info("  ✓ Generated security_headers.conf");
}
