import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { glob } from "glob";
import type { CspData } from "./types.js";

/**
 * finalizeCspConfig: Generates security_headers.conf with simplified CSP using Nonces
 */
export async function finalizeCspConfig(distDir: string, cspData: CspData) {
  console.log("[PostBuild] Finalizing CSP and Security Headers...");

  // Standalone JS files hashing (optional but kept for extra security on 'self' assets)
  const scriptHashes = new Set<string>();
  const jsFiles = await glob("**/*.js", { cwd: distDir, absolute: true });
  for (const file of jsFiles) {
    const c = fs.readFileSync(file);
    const h = crypto.createHash("sha512").update(c).digest("base64");
    scriptHashes.add(`'sha512-${h}'`);
  }

  // Note: HTML inline scripts/styles are now handled via Nonces, so we don't collect their hashes here.

  const imgSrc = Array.from(cspData.imageDomains)
    .map((d) => `https://${d}`)
    .join(" ");

  // Modern and Strict CSP
  const cspHeader = [
    "default-src 'none'",
    `script-src 'self' 'nonce-$cspNonce'`,
    `style-src 'self' 'unsafe-hashes' 'nonce-$cspNonce'`,
    imgSrc
      ? `img-src 'self' data: ${imgSrc} https://*.jmrp.io`
      : "img-src 'self' data: https://*.jmrp.io",
    "font-src 'self' data:",
    "connect-src 'self' https://api.github.com https://cloudflareinsights.com",
    "media-src 'self'",
    "manifest-src 'self'",
    "frame-src 'none'",
    "object-src 'none'",
    "base-uri 'self'",
    "form-action 'self'",
    "frame-ancestors 'none'",
    "upgrade-insecure-requests",
    "report-uri /csp-report",
  ]
    .map((s) => s.trim())
    .join("; ");

  const permissionsPolicy = [
    "accelerometer=()",
    "autoplay=()",
    "browsing-topics=()",
    "camera=()",
    "encrypted-media=()",
    "fullscreen=()",
    "geolocation=()",
    "gyroscope=()",
    "magnetometer=()",
    "microphone=()",
    "midi=()",
    "payment=()",
    "picture-in-picture=()",
    "publickey-credentials-get=(self)",
    "sync-xhr=()",
    "usb=()",
    "xr-spatial-tracking=()",
  ].join(", ");

  const content = `# Security Headers Configuration Generated by Astro Post-Build Integration

# HSTS (Strict Transport Security)
add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;

# Anti-Sniffing
add_header X-Content-Type-Options "nosniff" always;

# Frame Options (Prevent Clickjacking)
add_header X-Frame-Options "DENY" always;

# XSS Protection
add_header X-XSS-Protection "1; mode=block" always;

# Referrer Policy
add_header Referrer-Policy "strict-origin-when-cross-origin" always;

# Cross-Origin Policies
add_header Cross-Origin-Opener-Policy "same-origin" always;
add_header Cross-Origin-Resource-Policy "same-origin" always;

# Security Cookie (Dummy session cookie with security flags)
add_header Set-Cookie "__Host-Session=1; path=/; Secure; HttpOnly; SameSite=Strict" always;

# Content Security Policy (Nonce-based)
add_header Content-Security-Policy "${cspHeader}" always;

# Permissions Policy
add_header Permissions-Policy "${permissionsPolicy}" always;
`;

  fs.writeFileSync(path.join(distDir, "security_headers.conf"), content);
  console.log("  ✓ Generated security_headers.conf");
}
