sonar.organization=jmrplens
sonar.projectKey=jmrplens_jmrp.io
sonar.host.url=https://sonarcloud.io

# Source code location
sonar.sources=src

# Encoding
sonar.sourceEncoding=UTF-8

# Exclusions
sonar.exclusions=dist/**,node_modules/**,public/**,**/*.d.ts,.scannerwork/**,.sonar/**
sonar.coverage.exclusions=**

# Javascript/Typescript specific
sonar.typescript.tsconfigPath=tsconfig.json

# Quality Gate - Fail on new issues
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300

# New Code Definition
sonar.newCode.referenceBranch=main