/**
 * Accessibility Test Suite (Main Axe-core Scan)
 *
 * Performs automated accessibility scanning using Axe-core on every page
 * discovered in the sitemap. Each page is an independent test, enabling
 * Playwright to run them in parallel across multiple workers.
 *
 * Theme is controlled by the THEME env var (default: "light").
 *
 * Detailed HTML reports and a summary JSON are generated in the
 * `accessibility-report/` directory via the globalTeardown script.
 */

import * as fs from "node:fs";
import * as path from "node:path";

import AxeBuilder from "@axe-core/playwright";
import { expect, test } from "@playwright/test";
import { createHtmlReport } from "axe-html-reporter";

import type { PageAccessibilityResult, PageInfo } from "./utils";
import { getCachedPages } from "./utils";

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------
const REPORT_DIR = "accessibility-report";
const RESULTS_DIR = path.join(REPORT_DIR, ".results");
const theme = process.env.THEME === "dark" ? "dark" : "light";

// ---------------------------------------------------------------------------
// Read pages synchronously — cache is pre-generated by globalSetup.
// Applies locale filtering via LOCALE_FILTER env var.
// Falls back to empty array when listing tests without running globalSetup.
// ---------------------------------------------------------------------------
const pages: PageInfo[] = getCachedPages();

// ---------------------------------------------------------------------------
// Register one test per page for parallel execution across workers
// ---------------------------------------------------------------------------
test.describe("Accessibility Tests (Axe-core WCAG 2.1 AA)", () => {
  for (const pageInfo of pages) {
    test(`[${theme}] ${pageInfo.name}`, async ({ page: browserPage }) => {
      // Force color scheme
      await browserPage.emulateMedia({
        colorScheme: theme === "dark" ? "dark" : "light",
      });

      await browserPage.goto(pageInfo.url);
      await browserPage.waitForLoadState("domcontentloaded");

      // Apply theme to the document
      await browserPage.evaluate((t) => {
        document.documentElement.dataset.theme = t;
        document.documentElement.classList.toggle("dark", t === "dark");
      }, theme);

      await browserPage.evaluate(() => document.fonts.ready);

      const accessibilityScanResults = await new AxeBuilder({
        page: browserPage,
      })
        .exclude(["svg", "vite-error-overlay"])
        .withTags([
          "wcag2a",
          "wcag2aa",
          "wcag21aa",
          "wcag22aa",
          "best-practice",
        ])
        .options({ iframes: true })
        .analyze();

      const safeName = pageInfo.name
        .replaceAll(/[^a-z0-9]/gi, "_")
        .toLowerCase()
        .replaceAll(/(^_+)|(_+$)/g, "");
      const reportFileName = `${safeName}-${theme}.html`;

      createHtmlReport({
        results: accessibilityScanResults,
        options: {
          projectKey: `JMRP.io (${theme})`,
          outputDir: REPORT_DIR,
          reportFileName,
        },
      });

      // eslint-disable-next-line playwright/no-conditional-in-test
      if (accessibilityScanResults.violations.length > 0) {
        await browserPage.screenshot({
          path: `${REPORT_DIR}/${safeName}-${theme}-failure.png`,
          fullPage: true,
        });
      }

      // Write per-page result for aggregation in globalTeardown
      const result: PageAccessibilityResult = {
        page: `${pageInfo.name} (${pageInfo.url})`,
        name: pageInfo.name,
        url: pageInfo.url,
        violations: accessibilityScanResults.violations.length,
        incomplete: accessibilityScanResults.incomplete.length,
        violationIds: accessibilityScanResults.violations.map((v) => v.id),
        reportPath: reportFileName,
        detailedViolations: accessibilityScanResults.violations,
        detailedIncomplete: accessibilityScanResults.incomplete,
      };

      fs.writeFileSync(
        path.join(RESULTS_DIR, `${safeName}-${theme}.json`),
        JSON.stringify(result),
      );

      // Fail if any violations exist
      expect(
        accessibilityScanResults.violations,
        `${pageInfo.name} has ${accessibilityScanResults.violations.length} accessibility violations`,
      ).toEqual([]);
    });
  }
});
